language: java
env:
  - MAVEN_VERSION=3.3.9
  - MAVEN_VERSION=3.5.4
  - MAVEN_VERSION=3.6.0
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
dist: trusty
install:
  - "mvn -N io.takari:maven:0.6.1:wrapper -Dmaven=${MAVEN_VERSION}"
  - "./mvnw -U --show-version --errors --batch-mode test-compile dependency:go-offline"
script: "./mvnw -U --show-version --errors --batch-mode clean verify -Dinvoker.streamLogs=true"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - slachiewicz@apache.org

after_failure:
  - "cat /home/travis/build/mojohaus/animal-sniffer/animal-sniffer-maven-plugin/target/it/using-multi-release-jar/build.log"
